### ISSUE TITLE
neither `gap makedoc.g` nor `gap maketest.g` work

### ISSUE THREAD

**Issue by mohamed-barakat** [kamalsaleh/NConvex#1]

**Comment by mohamed-barakat** [comment]
`gap makedoc.g` is not working, since the file `doc/intros.autodoc` is missing in the repo. You didn't notice this since all `doc/*` is ignored in `.gitignore`, which is a bad style. You should only ignore the files which are automatically generated, otherwise you will oversee files you need to add.

**Comment by mohamed-barakat** [comment]
Now I have less differences in `gap maketest.g`:

```
########> Diff in [ "./doc/_Chapter_Cones.xml", 261, 386 ]
# Input is:
List( last, RayGenerators );
# Expected output:
[ [ [ -2, 5 ] ], [ [ 2, 7 ] ] ]
# But found:
[ [ [ 2, 7 ] ], [ [ -2, 5 ] ] ]
########
########> Diff in [ "./doc/_Chapter_Cones.xml", 261, 386 ]
# Input is:
Display( H );
# Expected output:
H-representation
begin
   2 X 3  rational

   0   5   2
   0  -7   2
end
# But found:
H-representation
begin
   2 X 3  rational

   0  -7   2
   0   5   2
end
########
```

**Comment by mohamed-barakat** [comment]
Please also add `maketest.g` to `.gitignore`.

**Comment by kamalsaleh** [comment]
moving maketest.g --> .gitignore is done!

Maybe the two difference is due to an old version of CddInterface, I get the test done without any mention of any differences!.  Maybe rebuilding the c conde in CddInterface would help.

It is enough to do the following to rebuild it,

    ./autogen.sh
    ./configure --with-gaproot=path/to/gaproot --with-cddlib=$(pwd)/cddlib/build
    make

**Comment by mohamed-barakat** [comment]
Excellent. It worked after generating the VERSION file. See kamalsaleh/CddInterface/pull/6.
