### ISSUE TITLE
IsRegular for fan

### ISSUE THREAD

**Issue by HereAround** [kamalsaleh/NConvex#3]
Currently IsRegular checks if a fan is smooth. This is not the correct property. Rather it should test if the fan is the normal fan of a polytope (cf. Convex package).

**Comment by kamalsaleh** [comment]
The method that is already there is taken from the definition of regular fan in Toric Varieties of Cox, 
which states that IsRegular <--> IsSmooth.

Now the method is changed, and IsRegular for fans tests if the fan is normal or not, which is what you need in toric varietes. Take a look at this commit please,

https://github.com/kamalsaleh/NConvex/commit/80af5925937541ab14eb353ffaa30fc881d3d7c5
