### ISSUE TITLE
Error from IsRegularFan

### ISSUE THREAD

**Issue by HereAround** [kamalsaleh/NConvex#5]
The following code worked in the past and should produce test = false:

LoadPackage( "NConvex" );
rays := [ [1,0,0], [-1,0,0], [0,1,0], [0,-1,0], [0,0,1], [0,0,-1],
          [2,1,1], [1,2,1], [1,1,2], [1,1,1] ];
cones := [ [1,3,6], [1,4,6], [1,4,5], [2,3,6], [2,4,6], [2,3,5], [2,4,5],
           [1,5,9], [3,5,8], [1,3,7], [1,7,9], [5,8,9], [3,7,8],
           [7,9,10], [8,9,10], [7,8,10] ];
F := Fan( rays, cones );
test := IsRegularFan( F );

However, I run into the following error:

Error, <n> must be a non-negative integer (not a integer) in
  return_list := Concatenation( return_list, ListWithIdenticalEntries( e - Length( b ) - c, 0 ) )
 ; at /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/NConvex/gap/NFan.gi:678 called from 
embed( nd, rays[r], i, - rays[r], ambient_dim * (j - 1) ) at /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/NConvex/gap/NFan.gi:721 called from
func( C[i] ) at /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/lib/coll.gi:665 called from
List( L1, function ( j )
      return embed( nd, rays[r], i, - rays[r], ambient_dim * (j - 1) );
  end ) at /home/i/HDD/Computer/Mathematics_software/gap-4.10.0/local/pkg/NConvex/gap/NFan.gi:721 called from
<function "unknown">( <arguments> )
 called from read-eval loop at error.gi:9

I am using gap 4.10.0,  ToricVarieties 2018.10.12 and NConvex 2018.06.15.

[I pulled NConvex from https://github.com/homalg-project/NConvex.]

Update:
This error remains if I use NConvex from https://github.com/kamalsaleh/NConvex.git/master with af3123899aec933e039b201a401494f5817fe54f (January 16).

**Comment by kamalsaleh** [comment]
Thank you Martin for reporting this. This issue is solved in this commit:

`https://github.com/kamalsaleh/NConvex/commit/c81a82879f3704c681af426f44dc002650d01075`
