### ISSUE TITLE
Suggestion for improved docu on PolytopeByInequalities

### ISSUE THREAD

**Issue by HereAround** [kamalsaleh/NConvex#6]
The documentation of the package currently says this function "takes a list in which every entry represents an inequality". I do not (yet) understand what exactly the expected syntax input for one inequality is. Certainly, this could be improved with a few more words or examples. Here is one example to clarify what I mean:

Example:
PolytopeByInequalities( [[1,-1],[0,1]] )

If I am not mistaken this corresponds to those real numbers m with

1 \leq -m & 0 \geq m

So my guess is that [ 1, -1 ] tells to compare a real number against the number 1 (first argument) whilst the second argument tells us if we choose \geq or \leq to form the inequality. Likewise for [ 0, 1 ]. Is that correct?

Likewise, an example on a polytope in R^2 could help to clarify how this generalizes to higher dimensions. I would appreciate such examples in the documentation.

**Comment by kamalsaleh** [comment]
A detailed explanation is now included in the documentation.
